# -*- coding: utf-8 -*-
"""01_SimpleApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1abzttpBgDiVfZQypa4eiIsGelUZd5FHk

#simple app-ngrok로 연결

### ngrok를 사용하기 위한 과정
"""

!pip install flask-ngrok
#!pip install flask-ngrok > /dev/null 2>&1

!pip install pyngrok

from google.colab import files
up=files.upload()

with open('ngrok_auth.txt') as nf:
  ngrok_auth=nf.read()

!ngrok authtoken $ngrok_auth

"""### 이 이후부터는 심플 웹 서버를 만드는 과정"""

from flask import Flask
from flask_ngrok import run_with_ngrok #ngrok를 사용할 때만 사용

app= Flask(__name__)
run_with_ngrok(app) #ngrok를 사용할 때만 사용, start ngrok when app is running.

@app.route('/')
def hello():
  return '<h1>hello world!</h1>'

if __name__=='__main__':
  app.run()